name: David Ebbo
description: Azure Web Sites, Kudu, ASP.NET and random other things
meta_description: "David Ebbo Site, Blogging about Azure Web Sites, Kudu, ASP.NET and random other things"

markdown: redcarpet
pygments: true
logo: false
paginate: 15

# Details for the RSS feed generator
url:            'blog url'
author:         'Your Name'
